sudo: required
services:
- docker
dist: trusty
env:
  global:
  - PKG_NEXUS_HOST=https://repo.cloud.ba.infn.it
  - PKG_UPLOAD_RPMS=1
  - secure: QTIuHI0NjtaeZeoWfgH2nOF5C4QTHDNsEIpj3gBq4f45evBK8VLflqp/rmkV9mLKDdVeMxb68mrz2ICEsn4ns8OnF//smNJpH6GhryexK7hi0DeEvbTZhgPZ1sE/pfrK8sqqEYVZE2r12oUTkrgE6EohpcWCO8pmmycsGuBKsi/6M86HuXtqdrFKA1g+LYsP1YPNnDUDi2gVPybQWQKrGtevcXR2ZN5Jd40osFskaX0BgQZLPQ5cgCXZa8rPfj8CELL4E7CEOLhSixADwAYcZFUgaut97X/v4RgWGgo+OxqNDXaYBpVo5dFEY9bxK94IbfhP7EtV5Azlz0M9GpaFfpEV5cn9P3tc3U3ZYhGFxM1d2zKaqOZR/1URBKtfZoqiOtP/pKOQROu/MPAc7Amu58HyoTmH/w+q/ZrwyqIEW4O+ymLCVBCoyHaagPlM+UlYMffBDJM49lrJuuzqKs66xmxGU7sv36++xEOCgfBWNZ7/QglF0HvC3FAM1TP+mCFxIPVd6wxRAyUe53feN7Qgz1SmqIpXfhWSwL1zunOmS1RB9uq/JjyPxpFBUimfxxKARyvgGpWHvijOB4aI4qf7/LV1NPFO8uXCTycP+v+EjiGG41tR60TcmeMazdZOvIvasUavYZ7Ly1AlGGy5kARrFduBf8fSyFuoMCa/PTzRRS8=
  - secure: cNySkzAeDum1pEkiqYQOMOUi2SB0/2JOD0pEmWKuLjM2DqfChBx7eYVpBuyNurQDimparmAM8/oYdSslyvGXTXJy3C+J5L/q0VHm6s+EfUG6NESbM4CISnYKZnuNbMT6ltRot8BE/mfCSE2Wvc8uvZTt0SRG6skefitaBSt/AFhFZW85CLdYqS18q7MQSReG5DubQD6MiplzCFBc49uGCw6cgkTMUcUhVyzy+hwse868pSY5zbggiamaG+wGOgf/rmE7QM1mNPE714DSFjhsFMfFjVktxqhtqRiUCnLQDmutL4sxoulNAzRog3Pza4E74vBFSVUMEbX41htCqAZvS/4Xj3UyZhUH4ROdQ7V5l8rW0P3QOnhPH7Q2dU00oD9wFTS3rMPAdyDMhmDefu2dPWa5D0uqmaw1Scam1J1/yYI0OWr4xJxeL8byXGq5bxtSJxbHfCniuO5KNLzVG4fhJT7rhytTkGfAbv3eQD4BCbxtHHLMDMA+649cyZrS7uLD4d5p7nqlZvz4hQN5ZcO1W5j34TU6Dw+xH6uR4iDmxs/8R3bTu0Yuc33LcmaNJRInF+1lFsTFAbYySpaqxVAhc+k0LOqfrvHFge+FpdAUHgCjVZFVFaT6bNvhhIAIM7r8t6S9/Nbmirjnj2WG0EQV/Yc6Jr2Jj5D6x6MQXwxe7Qw=
script:
- bash travis/build.sh
